### PR TITLE
package importer changed from default to source

### PR DESCRIPTION
**Pull request by alexgivi**
There was a problem when working with project located in private repository. Default importer usage caused panic after checking file error because of unability to import from private repo. Changing importer from Default to source fixes the problem.

### CODE REVIEW

**Comment by gtramontina** [comment]
Hey there @alexgivi! 👋 Thanks for giving it a crack! This is related to https://github.com/gtramontina/ooze/issues/9.

Unfortunately it seems to be more involved than changing to `source`. Indeed, it goes further and may even be enough for many situations. But it fails to handle scenarios where a function is called in one file but declared on a different file that hasn't been processed yet (you'll get what I'm saying if you run `make test.mutation` on your fork of Ooze).

I believe that in order to solve this problem we may need to re-think how we infect files. Also, this check is quite expensive to run for every infection; this contributes to having to re-think how infecting happens (memoization at some point).

I'm even considering dropping `v0.3.0` (`v0.2.0` works well, but without the [CancelNil](https://github.com/gtramontina/ooze/pull/8) virus) until this can be properly addressed.

Thoughts? 💭 

cc/ @blizzy78

**Comment by blizzy78** [comment]
> I believe that in order to solve this problem we may need to re-think how we infect files.

Yes. I'm working on that currently, and so far it looks quite promising, but it's not ready yet.
I seem to be running into some flaky tests in Ooze itself, but not quite sure yet.

> I'm even considering dropping `v0.3.0` (`v0.2.0` works well, but without the [CancelNil](https://github.com/gtramontina/ooze/pull/8) virus) until this can be properly addressed.

Agreed. The best course of action should be to disable CancelNil in the default list of viruses, then release a new version with a [retraction](https://go.dev/ref/mod#go-mod-file-retract) of 0.3.0 in go.mod.

Sorry for causing hickups 😅

**Comment by gtramontina** [comment]
> Sorry for causing hickups 😅

No worries! Version control systems exist for a good reason. 😄

I'll go ahead an release a retraction soon!

Cheers!

**Comment by alexgivi** [comment]
yes, i don't mind, thanks for care.

**Pull request closed without merging**
